junesung1004/dallaem

- package-lock.json
- package.json
- src/app/(home)/mypage/page.tsx
- src/app/components/ProgressBar/ProgressBar.tsx
**개요**
- 공통컴포넌트 ProgressBar 추가
**타입**
**작업 사항**
- 진행률을 나타내는 ProgressBar 컴포넌트를 추가하였습니다
- 진행도의 애니메이션 적용을 위해 `framer-motion` 라이브러리를 추가하였습니다
- ProgressBar 컴포넌트는 `색상`, `애니메이션 여부` 를 선택하여 활용할 수 있습니다
참고 명세 : https://www.notion.so/ProgressBar-19679e4031a680d6a09deb30675f2735?pvs=4
> feat: 공통컴포넌트 ProgressBar 추가

- src/app/(auth)/login/page.tsx
- src/app/(auth)/signup/page.tsx
- src/app/(home)/meeting/[id]/page.tsx
- src/app/(home)/mypage/@review/(..)mypage/create-review/[id]/page.tsx
- src/app/(home)/mypage/components/GlobalModal.tsx
- src/app/(home)/mypage/components/ReviewForm/ReviewForm.tsx
- src/app/(home)/mypage/page.tsx
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
> fix: 폴더 구조 수정 중

- commitlint.config.js
- src/components/Modal/Modal.tsx
**개요**
- 전역 모달 오픈 시 스크롤이 페이지 상단으로 강제 이동하는 현상을 수정하였습니다
**타입**
**작업 사항**
- `position: relative` -> `position: aboslute` 로 수정 
> fix: modal 오픈 시에 상단 스크롤 이동하는 버그 수정

- commitlint.config.js
- src/app/globals.css
- src/components/Button/Button.tsx
**개요**
- 버튼 hover 시 버튼 색상이 바뀌지 않는 현상과 `isFull` prop 이 제대로 동작하지 않는 현상을 수정하였습니다 
**타입**
**작업 사항**
- `isFull` 속성 적용을 위해 커스텀 클래스를 추가하였습니다
- 버튼 hover, active 시 적용되는 클래스를 문자열로 고정하였습니다
> fix: 버튼 hover 색상 안바뀌는 현상, `isFull` prop 적용 안 되는 현상 수정

- src/app/(home)/mypage/page.tsx
- src/components/HeartRatings/HeartRatings.tsx
- src/components/HeartRatings/HeartRatingsInteractive.tsx
**개요**
- HeartRatings 컴포넌트를 사용하는 컴포넌트에서 상태를 제어할 수 있도록 handleChange 핸들러를 추가하였습니다
**타입**
**작업 사항**
- 기존에 정적/동적 컴포넌트를 구분하던 `isInteractive` prop 을 삭제하고, `handleChange` prop 을 추가하여 구분하는 것으로 변경하였습니다
- 
> feat: HeartRatings 공통 컴포넌트 prop 변경(handleChange 핸들러 prop 추가)

- src/app/(home)/layout.tsx
- src/app/(home)/page.tsx
- src/app/globals.css
- src/components/MainCard/Card.tsx
- tailwind.config.ts
**개요**
- 공통 레이아웃을 변경하였습니다(figma padding 적용)
**타입**
**작업 사항**
- 폰트 적용 중복 코드 삭제
- 브레이크 포인트 설정
- `(hom) app `<main>` 클래스 변경
> style: 공통 레이아웃 변경

- next.config.ts
- src/app/(auth)/layout.tsx
- src/app/(auth)/login/page.tsx
- src/app/(auth)/signup/page.tsx
- src/components/GNB/Header.tsx
**개요**
- 로그인, 회원가입, GNB 공통 레이아웃을 변경
**타입**
**작업 사항**
- 로그인, 회원가입, GNB 공통 레이아웃을 변경하였습니다
> style: 공통 레이아웃 작업(로그인, 회원가입, GNB)

- src/api/detail-meeting/getDetailMeetingDate.ts
- src/app/(home)/meeting/[id]/page.tsx
- src/types/meetingDetail.ts
- src/types/paginationType.ts
**개요**
- 디테일 페이지 상세정보 API 호출
**타입**
**작업 사항**
- 상세페이지 이미지/시간/제목/장소 등 
더미데이터 -> API호출 로직으로 변경
> feat: datailpage API 연결

- src/api/meeting/getMeetingDate.ts
**개요**
버셀 배포 환경에서 api 받아오는 get요청 에러 발생 status 400 
**타입**
**작업 사항**
- 버셀 배포 환경에서 api 받아오는 get요청 에러 발생 status 400 
- 로컬 환경에서는 에러없이 잘 동작
> fix: vercel 배포 api 데이터 status 400 에러 발생

- next.config.ts
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
> fix: vercel 환경에서도 api 네트워크 에러 해결 성공

- src/api/detail-meeting/getDetailReviewData.ts
- src/app/(home)/meeting/[id]/page.tsx
- src/types/paginationType.ts
**개요**
- Detail Page Review 목록 API 연결
**타입**
**작업 사항**
- 디테일 페이지 리뷰 API 연결
리뷰 더미데이터 -> API 연결
> feat: detailpage Review API 연결

- src/app/(home)/mypage/page.tsx
- src/app/globals.css
- src/components/Button/Button.tsx
**개요**
- Button 공통 컴포넌트 변경(link 태그 대응, varataion prop 추가) 하였습니다
**타입**
**작업 사항**
- `state` 와 `isOutlined` prop 을 제거하였습니다
- `varation` 으로 버튼의 스타일 타입을 지정할 수 있도록 `varation` prop 을 추가하였습니다
- `variation` prop 의 기본 값은 'default'입니다
- 버튼 기본 스타일의 재사용성을 위하여 `global.css` 에 커스텀 클래스`btn-default` 를 추가하였습니다
> feat: Button 공통 컴포넌트 변경(link 태그 대응, varataion prop 추가)

- src/api/detail-meeting/getDetailMeetingDate.ts
**개요**
- base url 변경으로 api 경로 수정
**타입**
**작업 사항**
> fix: base url 변경으로 api 경로 수정

- src/app/(home)/layout.tsx
**개요**
- 전체 layout 색상 변경
**타입**
**작업 사항**
- 전체 layout 색상 변경
> chore: 전체 layout background 색상 변경

- src/app/(home)/mypage/@profile/(.)my-profile/page.tsx
- src/app/(home)/mypage/@review/(..)mypage/create-review/[id]/page.tsx
- src/app/(home)/mypage/components/ProfileIcon/ProfileIcon.tsx
- src/components/Modal/Modal.tsx
- src/lib/ModalProvider.tsx
**개요**
- 빌드 오류 수정
**타입**
**작업 사항**
- `Modal` 관련 import 에러 수정
- `ProfileIcon` size, className 선택 props로 변경
> fix: 빌드 오류 수정

- src/app/(home)/all-reviews/page.tsx
- src/app/components/Calendar/CalenderImage.tsx
- src/components/Filtering/FIlterList.tsx
- src/components/Filtering/Filter.tsx
**개요**
공통 컴포넌트 filtering을 수정했습니다!
**타입**
**작업 사항**
- Filter.tsx 파일을 css, 기능들을 추가, 수정하였습니다. 
- 기존 page.tsx에서 Filter.tsx로만 가져오는 방식에서, FilterList를 가져오는 방식으로 변경해 팀원들의 컴포넌트 사용성 높이려 다시 구현하였습니다.
- CalendarImage 코드를 수정해 날짜를 초기화, 적용하는 기능을 추가했습니다.
+ css에서 공통 컴포넌트 버튼으로 교체하고 좀 어그러지는 부분이 있는데 추후에 조금 수정을 해야 할 것 같습니다... 
- 스크린샷
> feat: filtering 컴포넌트 수정

- src/api/detail-meeting/getDetailMeetingDate.ts
- src/api/detail-meeting/getDetailReviewData.ts
- src/app/(home)/meeting/[id]/page.tsx
- src/app/(home)/meeting/_components/Pagination.tsx
**개요**
- detail 페이지 review를 공통 컴포넌트로 변경
**타입**
**작업 사항**
- 공통컴포넌트로 개발된 review 컴포넌트로 대체
> feat: detail review 공통 컴포넌트로 변경

- src/app/(home)/meeting/[id]/page.tsx
**개요**
- test
**타입**
**작업 사항**
> test: vercel test

- src/components/GNB/Header.tsx
- src/components/Login/Login.tsx
- src/store/useAuthStore.tsx
- src/types/userType.ts
**개요**
- 간단한 PR 요약 내용
유저 상태관리 변수 수정 및 추가
**타입**
**작업 사항**
유저 상태관리 변수 수정 및 추가 + set 함수
interface Store {
isLoggedIn: boolean;
token: string | null;
userId: number | null; // number로 변경
email: string | null; //이하 새로 추가됨
name: string | null;
companyName: string | null;
image: string | null;
setIsLoggedIn: (status: boolean) => void;
setToken: (newToken: string | null) => void;
setUserId: (id: number | null) => void;
setUserNull: () => void;
}
> feat: 유저 상태관리 변수 수정 및 추가

- src/api/meeting/getMeetingDate.ts
- src/components/MainCard/CardList.tsx
- src/hooks/customs/useMainCard.ts
- src/types/createMeetingType.ts
- src/types/meetingsType.ts
**개요**
feat: 모임 목록 get 요청 부분 공통 함수화 적용
**타입**
**작업 사항**
getMeeting 데이터 패치 공통 로직으로 수정
> feat: 모임 목록 get 요청 부분 공통 함수화 적용

- src/api/getReveiwScore.ts
- src/app/(home)/all-reviews/_components/reviewScores.tsx
- src/app/(home)/all-reviews/page.tsx
- src/components/ReviewCard/ReviewCard.tsx
- src/constants/index.ts
- src/types/pageComponentType.ts
- src/types/reviewType.ts
**개요**
리뷰 페이지 구성 및 평균 평점 조회 컴포넌트를 구현하였습니다.
**타입**
**작업 사항**
- 리뷰 페이지에 공통 컴포넌트, 개인 컴포넌트를 조합하여 화면을 구성하였습니다.
- 평균 평점 조회 컴포넌트를 구현하였습니다. (api로 데이터를 넣어놨고 추후에 react-query로 대체할 예정입니다.)
- 멘토링 피드백을 통해 constants안에 있는 타입들을 옮기고, api에 사용할 type을 작성했습니다.
- 반응형 오류로 인해 리뷰 카드 css를 변경하였습니다.
- 스크린샷
> feat: 리뷰 페이지 구성 및 평균 평점 조회 

- src/app/(home)/meeting/_components/footer.tsx
- src/components/Button/LikeButton.tsx
- src/hooks/customs/useLike.ts
- src/lib/likeStorage.ts
**개요**
- 좋아요 버튼 local에서  회원관리 -> zustand에서 회원관리
**타입**
**작업 사항**
- localstorage에서 회원ID 관리를 zustand에서 회원ID 관리로 로직 변경
- footer 에서 주최자인지 판별 '회원ID' == 'createdBy'
여기서 사용되는 '회원ID' 도 zustand에서 관리 로직으로 변경
> feat: 좋아요 버튼 회원원ID zustand에서 관리

- src/components/Badge/DateBadge.tsx
**개요**
- dateBadge button태그 span태그로 변경
**타입**
**작업 사항**
- dateBadge button태그 span태그로 변경
> dateBadge button태그 span태그로 변경

- src/api/detail-meeting/joinGroup.ts
- src/app/(home)/meeting/_components/footer.tsx
**개요**
- 디테일 페이지 참가자 기준 api 호출
**타입**
**작업 사항**
- 디테일 페이지 참가자 기준 api 호출
> feat: detail page footer 참가자 api 연결

- src/api/meeting/getMeetingDate.ts
- src/app/(home)/favorite-meetings/layout.tsx
- src/app/(home)/favorite-meetings/meetingService.tsx
- src/app/(home)/favorite-meetings/page.tsx
- src/types/meetingsType.ts
**개요**
- 찜한 모임 페이지를 구현하였습니다
**타입**
**작업 사항**
- 로그인한 사용자의 userId 기준, 로그인하지 않은 사용자의 guestId 기준 찜한 모임을 id 값으로 조회합니다
- 모임 종류 필터링이 하드코딩되어 있어서 전역 필터 상태가 수정되면 적용할 예정입니다
> wip 찜한 모임 페이지 구현

- src/app/(home)/all-reviews/page.tsx
- src/hooks/customs/useFetchReviews.tsx
- src/service/reviewService.ts
**개요**
리뷰 부분에서 사용할 api 공통화 부분 수정 및 커스텀 훅 추가
**타입**
**작업 사항**
- 리뷰 관련 api 공통화 작업 코드 수정
- 모든 리뷰에서 사용할 api 커스텀 훅 작성
> feat: api 공통화 코드 수정 및 커스텀 훅 추가

- src/app/(home)/_components/HomeFilter.tsx
- src/components/MainCard/Card.tsx
- src/components/MainCard/CardList.tsx
**개요**
- 모임 참여하기 관련 데이터 카드 컴포넌트에 적용 및 마감 모임 표시 추가
**타입**
**작업 사항**
1. 모임 참여하기 api 적용 후 카드 컴포넌트 member, langeBar 적용
2. 모집 마감이 완료된 경우 모집이 끝났다는 UI 적용
> feat: 모임 참여하기 관련 데이터 카드 컴포넌트에 적용 및 마감 모임 표시 추가

- package-lock.json
- package.json
- src/api/detail-meeting/cancelGroup.ts
- src/api/detail-meeting/participantsGroup.ts
- src/app/(home)/meeting/[id]/page.tsx
- src/app/(home)/meeting/_components/footer.tsx
**개요**
- 회원 / 비회원 / 주최자 / 참여자 관련하여 api호출
**타입**
**작업 사항**
- 회원 / 비회원 / 주최자 / 참여자 관련하여 api호출
> footer api 연결

- src/app/(home)/meeting/[id]/page.tsx
- src/app/(home)/meeting/_components/MeetingCard.tsx
- src/app/(home)/meeting/_components/footer.tsx
- src/types/meetingDetail.ts
**개요**
- 카드 디테일 컴포넌트 조합
**타입**
**작업 사항**
- 카드 디테일 컴포넌트 조합
> feat: 카드 디테일 컴포넌트 조합

- .vscode/settings.json
- next.config.ts
- src/app/(home)/mypage/@profile/(.)my-profile/page.tsx
- src/app/(home)/mypage/@review/(..)mypage/create-review/[id]/page.tsx
- src/app/(home)/mypage/components/CardList/CardBase.tsx
- src/app/(home)/mypage/components/CardList/CardList.tsx
- src/app/(home)/mypage/components/CardList/Services/myMeetingService.ts
- src/app/(home)/mypage/components/MyPageNav/MyPageNav.tsx
- src/app/(home)/mypage/components/ProfileForm/ProfileForm.tsx
- src/app/(home)/mypage/components/ProfileHeader/ProfileHeader.tsx
- src/app/(home)/mypage/createdMeetings/page.tsx
- src/app/(home)/mypage/layout.tsx
- src/app/(home)/mypage/meetings/page.tsx
- src/app/(home)/mypage/reviews/page.tsx
- src/app/(home)/mypage/reviews/writable/page.tsx
- src/app/(home)/mypage/reviews/written/page.tsx
- src/components/Modal/Modal.tsx
- src/hooks/customs/useMyMeetings.tsx
- src/hooks/customs/useMyReviews.ts
- src/lib/ModalProvider.tsx
- src/types/createMeetingType.ts
- src/types/reviewType.ts
**개요**
- 마이페이지 기능 추가 후 진입되지 않는 버그를 수정하였습니다
**타입**
**작업 사항**
- 마이페이지 나의 모임/나의 리뷰/내가 만든 모임 조회 기능을 추가하였습니다
- 버전이 너무 오래 된 이슈로 PR 후 머지 한 다음 남은 작업 진행하겠습니다
- 남은 작업
- 1. 프로필 회사명 onChange 로 제어 및 수정 기능
- 2.  '나의 리뷰' 진입 시 필터링 기본 값 처리
- 3. '내가 작성한 리뷰 ' 이미지 없을 시의 처리
- 4. 각 탭 별 이동간 `loading` 상태 처리
- 5. '나의 모임' 예약 취소 기능 추가
- 6. 비회원의 마이페이지 진입 처리 
> fix: 마이페이지 기능 추가 후 진입 안 되는 버그 수정

- cody.json
- package-lock.json
- package.json
- src/components/MainCard/CardList.tsx
- src/hooks/customs/useMainCard.ts
- src/hooks/customs/useMeeting.tsx
**개요**
useEffect 제거
**타입**
**작업 사항**
> fix: useEffect 제거

- src/api/detail-meeting/cancelGroup.ts
- src/app/(home)/meeting/[id]/page.tsx
- src/app/(home)/meeting/_components/AttendeeProfiles.tsx
- src/app/(home)/meeting/_components/MeetingCard.tsx
- src/app/(home)/meeting/_components/footer.tsx
- src/components/ProgressBar/ProgressBar.tsx
**개요**
- MeetingData props 실시간 반영
**타입**
**작업 사항**
- '참여하기' '참여하기 취소' 버튼 눌렀을때, participantCount props가 실시간으로 변하도록 코드 수정
> feat: MeetingData props 실시간 반영

- src/api/getReveiwScore.ts
- src/app/(home)/all-reviews/_components/ReviewCardList.tsx
- src/app/(home)/all-reviews/_components/ReviewSummary.tsx
- src/app/(home)/all-reviews/_components/reviewScores.tsx
- src/app/(home)/all-reviews/page.tsx
- src/hooks/customs/useFetchReviews.tsx
- src/hooks/query/useFetchReviewsScore.tsx
- src/store/useInputSelectFilterStore.tsx
- src/types/reviewType.ts
**개요**
모든 리뷰 페이지 관련 api를 추가하고, 관련 컴포넌트를 구현했습니다.
**타입**
**작업 사항**
- 리뷰 데이터 api를 custom hook으로 추가해, 필터링에 의한 파라미터 변경 시 리뷰 데이터에 반영되게 구현하였습니다.
- 리뷰 데이터를 렌더링 할 수 있는 ReviewCardList를 구현하였습니다.
- 리뷰 평균 평점, 리뷰 개수 api를 수정하고, react-query를 추가하였습니다.
- 리뷰 평균 평점, 리뷰 개수를 한눈에 볼 수 있는 ReviewScores의 값 들을 type 변경 시  동적으로 반영할 수 있게 변경하였습니다.
- 리뷰 관련 type, store의 초기값을 변경하였습니다.
- 스크린샷
> feat: 모든 리뷰 관련 api추가 및 컴포넌트 구현

- src/app/(home)/favorite-meetings/meetingService.tsx
- src/components/MainCard/CardList.tsx
- src/hooks/customs/useMainCard.ts
**개요**
- 사용자가 찜한 모임이 없을 경우 발생하는 오류를 수정하였습니다
**타입**
**작업 사항**
- JSON parse 에러로 발생하는 요청 오류를 처리하였습니다
- `getLocalStorageItem` 유틸 함수 추가
- 로그인 전역 상태 관리 값이 변경된 후에 찜한 모임에 대한 API를 요청할 수 있도록 `useMainCard` hook을 수정하였습니다
- 찜한 모임 아이템 없을 때 map() 오류 수정
> fix: 찜한 모임 페이지 오류 수정

- src/app/(home)/meeting/_components/footer.tsx
- src/hooks/customs/useGroupActions.ts
**개요**
- refactor: footer 컴포넌트 로직 세분화
**타입**
**작업 사항**
- footer 컴포넌트 로직 세분화
공통 로직 커스텀훅을 통해 공통화
> refactor: footer 컴포넌트 로직 세분화

- src/components/Filtering/Filter.tsx
- src/components/ReviewCard/ReviewCard.tsx
**개요**
리뷰 카드의 내용들을 피그마에 적힌 형식대로 수정하고, css 수정이 필요한 컴포넌트 css 코드를 변경하였습니다.
**타입**
**작업 사항**
- 리뷰 카드의 내용들을 피그마에 나온 형식대로 수정하는 코드를 추가하였습니다. (날짜, 타입 수정)
- Filter 컴포넌트 부분에서 캘린더가 일정 px에서 넘어가는 문제 때문에 반응형이 깨지는 css 부분을 수정하였습니다.
- 리뷰 카드의 유저 이미지, 별점 부분 css 수정하였습니다.
**스크린샷**
<리뷰 카드>
<캘린더>
https://github.com/user-attachments/assets/f739a86e-e07a-4567-9a5a-485b99338799
> feat: ReviewCard 내용 형식에 맞게 변경 + style: ReviewCard, Filter 컴포넌트  css 변경

- src/components/MainCard/CardListInfinite.tsx
- src/lib/ReactQueryProvider.tsx
**개요**
- staleTime, gcTime 변경 및 카드 제목 수정
**타입**
**작업 사항**
1. 리액트 쿼리 초기 설정 - 전역으로 staleTime, gcTime을 관리하는데 수치 조절
2. 카드 컴포넌트 title 제목으로 변경
> feat: staleTime, gcTime 변경 및 카드 제목 수정

- src/components/Button/LikeButton.tsx
- src/hooks/customs/useLike.ts
- src/types/likeButtonType.ts
**개요**
- 좋아요 기능에 함수 props 추가
- 좋아요 눌렀을 때 알림기능 추가
**타입**
**작업 사항**
- 좋아요 기능에 함수 props 추가
- 좋아요 눌렀을 때 알림기능 추가
> feat: 좋아요 기능에 함수 props 추가

- src/api/meeting/createMeeting.ts
- src/app/(home)/_components/CreateMeetingForm.tsx
**개요**
- 모임 주최자가 모임을 만드는 동시에 자동 참여하는 로직 추가
**타입**
**작업 사항**
-  모임 주최자가 모임을 만드는 동시에 자동 참여하는 로직 추가
```js
src -> app -> (home) -> _components -> CreateMeeting.tsx
//모임 만들기 폼 작성 후 버튼을 클릭하면 업로드 되는 이벤트 핸들러 버튼
const clickUpdateMeetingHandler = async (
e: React.FormEvent<HTMLFormElement>,
) => {
e.preventDefault();
const formData = new FormData(e.currentTarget);
formData.append('location', meetingPlace);
formData.append('type', meetingSelectedService || '');
formData.append('name', meetingName);
formData.append('dateTime', meetingStartDate?.toISOString() || '');
formData.append('capacity', String(meetingPeople));
formData.append('registrationEnd', meetingEndDate?.toISOString() || '');
for (const [name, value] of formData) {
console.log(`${name} = ${value}`); // key1 = value1, then key2 = value2
} …
```
> feat: 모임 주최자가 모임을 만드는 동시에 자동 참여하는 로직 추가

- src/components/Badge/Badge.tsx
**개요**
- 공통 컴포넌트 Badge tailwind css 를 변경하였습니다
**타입**
**작업 사항**
- width 와 height 값을 고정값으로 변경하였습니다
> style: 공통 컴포넌트 Badge css 변경

- src/app/(home)/meeting/[id]/page.tsx
- src/app/(home)/meeting/_components/MeetingCard.tsx
- src/hooks/query/useDetailMeetingData.ts
- src/hooks/query/useDetailReviewData.ts
**개요**
- detail page react-query 적용
**타입**
**작업 사항**
- detail page의 전체 데이터, review 데이터를 react-query로 받음
> feat: detail page react-query 적용

- src/app/(home)/layout.tsx
**개요**
- 컨텐츠 영역에 일정 px 이상 넓어지지않도록 공통 레이아웃을 설정하였습니다
**타입**
**작업 사항**
- `src/app/(home)/layout.tsx` 에 한 번 더 감싼 `md:max-w-996px` 적용
> style: 공통 레이아웃 설정

- src/components/ProgressBar/ProgressBar.tsx
**개요**
- 모든 리뷰 페이지에서 탭이 변경될 때 프로그레스 바에 평점 수치가 변경되지 않는 현상을 수정하였습니다
**타입**
**작업 사항**
- useEffect() 에 isAnimate prop 속성이 false 일 경우 애니메이션 없이 prop으로 받은 value 값을 진행 상태에 바로 반영할 수 있도록 변경하였습니다
- `value` 값은 동일하지만 `max` 값이 변경되는 경우를 고려 필요. 테스트 중 해당 케이스 발생할 시 의존성 배열에 추가 예정
-
> fix: 모든 리뷰 페이지에서 공통 컴포넌트 ProgressBar 에 평균 평점 수치 적용 안되는 현상 수정

- src/components/GNB/Header.tsx
- src/components/Login/Login.tsx
- src/components/Signup/Signup.tsx
**개요**
- 간단한 PR 요약 내용
헤더에서 찜한모임 개수 알림
**타입**
**작업 사항**
- 모임을 찜할 경우 (알림 여부에 따라) 찜한 모임의 개수가 헤더에 나타나도록 하였습니다.
> feat: 헤더에서 찜한모임 개수 알림 추가, 기타 이슈 해결

- src/components/Dialog/Dialog.tsx
**개요**
- 마이페이지 모임 예약 취소 버튼 시 나타나는 모달 UI 의 버튼 색상을 변경하였습니다
**타입**
**작업 사항**
- 공통 컴포넌트 Button props 변경 사항 반영
- 
- 수정 이전
- 수정 이후
> style: 마이페이지 예약 취소 confirm 모달 버튼 UI 변경

- src/api/meeting/getMeetingDate.ts
- src/components/MainCard/CardListInfinite.tsx
- src/hooks/query/useHomeMeetingCardList.ts
**개요**
- 초기 페이지 설정 값, limit 값, api 호출 콘솔추가
**타입**
**작업 사항**
> fix: 초기 페이지 설정 값, limit 값, api 호출 콘솔추가

- src/components/Login/Login.tsx
**개요**
- 간단한 PR 요약 내용
로그인 유지 안되는 문제 해결
**타입**
- [V] 🐛fix: 버그, 오류 수정
**작업 사항**
로그인 시 상태가 전역변수에 저장되지 않는 문제를 해결했습니다
> fix: 로그인 유지 안되는 문제 해결

- src/app/(home)/_components/CreateMeetingForm.tsx
- src/hooks/mutation/useCreateMeeting.ts
**개요**
- 모임 생성하기 -> react mutation 로직 수정 및 새로고침 이슈 해결
**타입**
**작업 사항**
1. 기존 일반 fetch를 사용하여 모임을 업로드하는 방식을 -- > react-mutation 방법으로 수정
2. ssr 페이지에서 업데이트를 하면 무조건 새로고침을 눌러야 반영이 되었던 현상을 mutation이 성공하면 invalidateQueries 함수를 호출해 해당 key 값을 가져와 새로고침을 안해도 적용이 되게 수정함
3. isError, isPending 을 활용하여 비동기 후 처리 코드를 추가하여 UX 상승되게 로직 추가함.
- 모임 생성하는 mutaion 코드
```js
src -> hooks -> mutation -> useCreateMeeting.ts
'use client';
import { createMeeting } from '@/api/meeting/createMeeting';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'next/navigation';
export const useCreateMeeting = () => {
const queryClient = useQueryClient();
const router = useRouter();
const mutation = useMutation({
mutationFn: createMeeting,
onSuccess: (res) => {
console.log('모임 생성 성공 : ', …
```
> feat: 모임 생성하기 -> react mutation 로직 수정 및 새로고침 이슈 해결

- package-lock.json
- package.json
- src/api/meeting/getMeetingDate.ts
- src/app/(home)/layout.tsx
- src/hooks/mutation/useCreateMeeting.ts
- src/hooks/query/useHomeMeetingCardList.ts
**개요**
- 모임 생성 시 성공 알림 추가로 UX 향상
**타입**
**작업 사항**
- 모임을 새로 생성하면 최신순으로 정렬되어 있는 상태가 아니라 업로드가 되었는지 확인 하기 힘듬
- 이러한 현상을 toast 라이브러리를 적용해 UX 경험을 상승시키기 위하여 도입
https://github.com/user-attachments/assets/ce7a0332-9ecd-435f-b28f-755fcd10228e
> feat: 모임 생성 시 성공 알림 추가로 UX 향상

- src/app/(home)/favorite-meetings/components/CardList/CardList.tsx
- src/app/(home)/meeting/_components/MeetingCard.tsx
- src/components/Badge/StatusBadge.tsx
- src/components/MainCard/CardList.tsx
- src/components/MainCard/CardListInfinite.tsx
**개요**
- status badge 조건 추가
**타입**
**작업 사항**
- status badge 조건 추가
> feat:status badge 조건 추가

- src/api/getReveiwScore.ts
- src/app/(home)/all-reviews/_components/ReviewSummary.tsx
- src/app/(home)/all-reviews/page.tsx
- src/constants/index.ts
- src/hooks/customs/useFetchReviews.tsx
- src/hooks/query/useFetchReviewData.tsx
- src/hooks/query/useFetchReviewsScore.tsx
- src/types/reviewType.ts
**개요**
모든 리뷰 관련 react-query를 추가하고 리뷰 평점 로직을 수정하였습니다!
**타입**
**작업 사항**
- 모든 리뷰 관련 리액트 쿼리를 추가했습니다.
- gatheringId 관련해서 평점 평균을 다시 계산하는 로직을 추가했습니다.
- 리액트 쿼리, 평점 평균 관련 타입과 상수 데이터를 추가, 수정 했습니다.
‼️평균 평점 관련 로직들은 기능만 작동하게 넣어놓은 상태라 추후에 훅이나 유틸로 빼서 리팩토링할 예정입니다~ ‼️
- 스크린샷
https://github.com/user-attachments/assets/884a00db-e7f9-4588-bdf1-50c92656290b
> feat: 모든 리뷰 관련 react-query 추가 및 리뷰 평점 로직 수정

- src/app/(auth)/login/page.tsx
- src/app/(auth)/signup/page.tsx
- src/components/GNB/Header.tsx
- src/components/Login/Login.tsx
- src/components/Signup/Signup.tsx
**개요**
- 간단한 PR 요약 내용
로그인, 회원가입 레이아웃 변경
**타입**
- [ V ] 🎨style: 코드 스타일 및 포맷 / CSS 등 사용자 UI 디자인 변경 (제품 코드 수정 발생, 코드 형식, 정렬 등의 변경)
**작업 사항**
피그마에 맞춰 레이아웃을 변경하였습니다
> style: 로그인, 회원가입 레이아웃 변경

- src/app/(home)/favorite-meetings/meetingService.tsx
- src/hooks/customs/useFavoriteMeetings.tsx
- src/hooks/customs/useLikeNotify.tsx
- src/types/likeButtonType.ts
- src/utils/localStorage.ts
**개요**
- utils 함수 디렉토리를 추가하여 로컬 스토리지 관련 함수를 공통화하였습니다
**타입**
**작업 사항**
- 로컬 스토리지에서 값을 가져오는 함수 추가
- 찜한 사용자를 가져오는 함수
- 찜한 모임 id를 삭제하는 함수
- util 함수 공통화, 기존 코드 제거
> feat: 로컬 스토리지 util 함수 추가

- src/api/reivews.ts
**개요**
- 리뷰 작성 모달에서 리뷰를 작성한 후 버튼을 눌렀을 때 동작하지 않고 POST 요청이 되지 않는 현상을 수정하였습니다
**타입**
**작업 사항**
- `.env` 파일 변경을 반영하지 않아서 발생한 버그이므로 반영하여 endpoint 변경
> fix: 리뷰 작성 POST 요청 안 되는 버그 수정

- src/_tests/Tag.tsx
- src/app/(home)/_components/Button.tsx
- src/app/(home)/_components/CreateMeetingForm.tsx
- src/app/(home)/meeting/_components/MeetingCard.tsx
- src/app/(home)/meeting/_components/footer.tsx
- src/app/(home)/mypage/components/ProfileForm/FormControl.tsx
- src/app/(home)/mypage/components/ProfileHeader/ProfileHeader.tsx
- src/app/(home)/mypage/components/ReviewForm/ReviewForm.tsx
- src/app/(home)/mypage/components/Tag/TagBase.tsx
- src/app/globals.css
- src/components/Badge/DateBadge.tsx
- src/components/Badge/DeadlineBadge.tsx
- src/components/Badge/StatusBadge.tsx
- src/components/Button/Button.tsx
- src/components/Filtering/FilterDropdown.tsx
- src/components/HeartRatings/Heart.tsx
- src/components/InputSection/InputWindow.tsx
- src/components/Login/Login.tsx
- src/components/MainCard/Card.tsx
- src/components/Members/Members.tsx
- src/components/ProgressBar/ProgressBar.tsx
- src/components/ReviewCard/ReviewCard.tsx
- src/components/Service/Service.tsx
- src/components/Signup/Signup.tsx
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- 서비스 메인 컬러 `orange-600` 을 `primary-600` 으로 색상 클래스 네임 변경
> style: tailwind config 에 추가된 대표 컬러로 수정

- src/_tests/Tag.tsx
- src/app/(home)/_components/Button.tsx
- src/app/(home)/_components/CreateMeetingForm.tsx
- src/app/(home)/meeting/_components/MeetingCard.tsx
- src/app/(home)/meeting/_components/footer.tsx
- src/app/(home)/mypage/components/ProfileForm/FormControl.tsx
- src/app/(home)/mypage/components/ProfileHeader/ProfileHeader.tsx
- src/app/(home)/mypage/components/ReviewForm/ReviewForm.tsx
- src/app/(home)/mypage/components/Tag/TagBase.tsx
- src/app/globals.css
- src/components/Badge/DateBadge.tsx
- src/components/Badge/DeadlineBadge.tsx
- src/components/Badge/StatusBadge.tsx
- src/components/Button/Button.tsx
- src/components/Filtering/FilterDropdown.tsx
- src/components/HeartRatings/Heart.tsx
- src/components/InputSection/InputWindow.tsx
- src/components/Login/Login.tsx
- src/components/MainCard/Card.tsx
- src/components/Members/Members.tsx
- src/components/ProgressBar/ProgressBar.tsx
- src/components/ReviewCard/ReviewCard.tsx
- src/components/Service/Service.tsx
- src/components/Signup/Signup.tsx
- tailwind.config.ts
**개요**
- tailwind config `colors` 속성에 디자인 토큰을 추가하였습니다
**타입**
**작업 사항**
- 디자인 토큰 컬러 `primary`, `secondary` 컬러 추가
> style: tailwind config color 디자인 토큰 추가

- src/components/GNB/Header.tsx
**개요**
- 헤더 배경색을 변경된 디자인 토큰을 반영하여 그라데이션 배경색으로 변경하였습니다
**타입**
**작업 사항**
- 헤더에 변경된 디자인 토큰 반영된 색상 그라디언트 배경색 적용
> style: 헤더 배경색 그라데이션으로 변경

- src/app/(home)/mypage/components/CardList/CardBase.tsx
- src/app/(home)/mypage/components/ReviewForm/ReviewForm.tsx
- src/app/(home)/mypage/components/ReviewForm/TextBox.tsx
- src/app/globals.css
**개요**
- 리뷰 작성 입력 폼 고정 높이를 추가하였습니다 
**타입**
**작업 사항**
- 리뷰 작성폼 textarea ui 변경
- 예약 취소하기 버튼 ui 변경
- tailwind `hide-scroll` 클래스 추가
-
> style: 리뷰 작성 폼 UI 수정

- src/app/(home)/_components/CreateMeetingForm.tsx
**개요**
fix: 오타 수정
**타입**
**작업 사항**
> fix: 오타 수정

- src/app/(home)/mypage/components/CardList/CardBase.tsx
- src/app/(home)/mypage/components/CardList/CardInfo.tsx
- src/app/(home)/mypage/components/CardList/CardList.tsx
- src/app/(home)/mypage/components/ReviewForm/ReviewForm.tsx
- src/app/(home)/mypage/components/ReviewForm/TextBox.tsx
- src/app/(home)/mypage/layout.tsx
- src/app/globals.css
**개요**
- 1차 QA[반응형 문제] 이슈 관련 반응형 UI 깨지는 현상을 수정하였습니다
- 리뷰작성하기 버튼 ui 변경
**타입**
**작업 사항**
- 반응형 깨지는 문제 수정
- 카드리스트 마지막 카드 컴포넌트 이후로 구분선 추가
- 마이페이지 ui 디자인 시안에 맞춰 배경색 흰색 적용
- 일부 사용하지 않는 div 제거
- 리뷰 작성하기 버튼 ui 변경
> style: 마이페이지 카드 컴포넌트 반응형 css 수정

- src/app/(home)/mypage/components/CardList/CardList.tsx
- src/app/(home)/mypage/createdMeetings/page.tsx
- src/app/(home)/mypage/loading.tsx
- src/app/(home)/mypage/meetings/page.tsx
- src/app/(home)/mypage/page.tsx
- src/app/(home)/mypage/reviews/page.tsx
- src/app/(home)/mypage/reviews/writable/page.tsx
- src/app/(home)/mypage/reviews/written/page.tsx
**개요**
- 마이페이지에 데이터가 없을 때에 대한 UI 예외 처리를 하였습니다
**타입**
**작업 사항**
> fix: 마이페이지 데이터 없을 때 UI 처리

- src/app/(home)/mypage/components/CardList/CardBase.tsx
- src/app/(home)/mypage/components/CardList/CreateReviewButton.tsx
**개요**
- 리뷰 생성 POST 요청 시 특정 모임 id로만 작성 요청하던 현상을 수정하였습니다
**타입**
**작업 사항**
- `리뷰 작성하기` 버튼 눌렀을 때 하드 코딩된 param 값으로 이동하는 코드 제거
- `CreateReviewButton` 컴포넌트에 `id` props 추가
> fix: 리뷰 생성 POST 요청 시 특정 모임 id로만 작성 요청하던 현상 수정

- src/app/(home)/mypage/components/CardList/CardBase.tsx
- src/app/(home)/mypage/components/CardList/Services/myMeetingService.ts
- src/hooks/customs/useMyMeetings.tsx
- src/types/meetingsType.ts
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
- fetchMeetings sortBy param 추가
- 취소되지 않은 모임만 보이도록 변경
> feat: 마이페이지 참여 시간이 지나지 않은 아이템이 상단에 보여지도록 변경

- src/components/Filtering/FIlterList.tsx
- src/components/Filtering/FilterDropdown.tsx
**개요**
필터링 관련 QA에서 나온 수정사항들과 다른 기능적인 부분을 수정하였습니다.
(필터링 버튼 배치, 드롭다운 밖 누르면 창 닫힘 + sortBy 라벨 별 sortOrder 설정)
**타입**
**작업 사항**
- 필터링 버튼 배치 css를 변경하였습니다.
- 드롭다운 밖 누르면 드롭다운 닫히는 기능을 추가하였습니다.
- 필터링 각 sortBy 이름에 맞게  sortOrder기본값을 수정하였습니다.
-> 마감 임박순은 sortOrder-asc, 다른 sortBy는 sortOrder-desc로 설정
https://github.com/user-attachments/assets/a85cda22-82ae-482b-b80d-66dfe1150f67
> feat:  QA 관련 필터링 기능 추가 

- src/components/PageNav/PageNavbar.tsx
**개요**
마이페이지-리뷰-서브아이템 선택 안되는 문제를 해결했습니다
**타입**
**작업 사항**
마이페이지-리뷰-서브아이템 선택 안되는 코드를 수정했습니다
https://github.com/user-attachments/assets/75a195c8-67b7-477b-83f4-13aeb0e9c12f
> fix: 마이페이지-리뷰-서브아이템 선택안되는 문제 해결

- src/app/(home)/meeting/_components/footer.tsx
**개요**
- button 태그를 Button 컴포넌트로 변경
**타입**
**작업 사항**
- button 태그를 Button 컴포넌트로 변경
> feat: Button 컴포넌트 사용

- src/app/(home)/meeting/[id]/page.tsx
**개요**
- feat: 종료 이후엔 footer 비활성화
**타입**
**작업 사항**
- feat: 종료 이후엔 footer 비활성화
> feat: 종료 이후엔 footer 비활성화

- src/app/(home)/all-reviews/ReviewsPage.tsx
- src/app/(home)/all-reviews/_components/ReviewCardList.tsx
- src/app/(home)/all-reviews/_components/ReviewSummary.tsx
- src/app/(home)/all-reviews/page.tsx
- src/hooks/query/useFetchReviewData.tsx
- src/service/reviewService.ts
**개요**
모든 리뷰 페이지 무한 스크롤 구현 및 모든 리뷰 페이지 리팩토링
**타입**
**작업 사항**
-  intersection observer를 이용한 무한 스크롤 구현
- page에서 initialData를 호출하고, ReviewPage라는 하위 컴포넌트를 만들어서 page 하나에서 하던 역할을 두 개로 분리하였습니다.
- 무한스크롤 변경으로 인해 변경된, 평균 평점 컴포넌트 수정
급하게 작업하다보니 볼륨이 커졌습니다ㅜㅜ 다음 작업부터 작은 PR 유지하겠습니다..!
깜빡임이 있어 추후에 애니메이션도 넣고, 리팩토링이 필요할 거 같습니다!
- 스크린샷
https://github.com/user-attachments/assets/8f2ae5a6-7460-45b5-ba00-fba554c6e0d2
> 모든 리뷰 페이지 무한 스크롤 구현

- src/components/Button/LikeButton.tsx
- tailwind.config.ts
**개요**
- feat: heart 애니메이션 추가
**타입**
**작업 사항**
- feat: heart 애니메이션 추가
> feat: heart 애니메이션 추가

- src/api/reivews.ts
- src/hooks/customs/useCreateReview.tsx
**개요**
- 사용자가 이미 리뷰를 작성한 모임에 리뷰를 작성할 때에 대해 예외 처리를 하였습니다
**타입**
**작업 사항**
- 에러 핸들링 code 403, 404, 400 대응
- 에러 텍스트를 받아서 처리하는 공통화된 로직이 필요할 거 같습니다😞
> fix: 사용자가 이미 리뷰를 작성한 모임에 리뷰를 추가할 시 예외 처리

- src/components/GNB/ProfileTooltip.tsx
**개요**
헤더 z-index 추가했습니다.
**타입**
**작업 사항**
헤더 드롭다운 z-index에 10 넣었습니다
- 스크린샷
> fix: 헤더 드롭다운 z-index 추가

- src/components/GNB/Header.tsx
**개요**
- 간단한 PR 요약 내용
알림뱃지 로그아웃시 사라지는 문제 해결
**타입**
- [ V ] 🐛fix: 버그, 오류 수정
**작업 사항**
알림뱃지 로그아웃시 사라지는 문제 해결
> fix: 알림뱃지 로그아웃시 사라지는 문제 해결

- src/app/(home)/all-reviews/ReviewsPage.tsx
- src/app/(home)/all-reviews/_components/ReviewCardList.tsx
- src/components/ReviewCard/ReviewCard.tsx
**개요**
무한 스크롤 적용 후 리뷰 카드 반응형 부자연스러운 부분을 수정하였습니다.
**타입**
**작업 사항**
리뷰 카드, 리뷰 리스트 css를 수정하고, 리뷰페이지의 불필요한 css를 삭제하였습니다.
- 스크린샷
https://github.com/user-attachments/assets/11c113f6-2f0c-4713-9da7-3b55641e6309
> style: 무한 스크롤 적용 후 모든 리뷰카드 반응형 깨짐 css 수정

- src/components/GNB/ProfileTooltip.tsx
**개요**
- 마이페이지 이외 페이지에서 프로필 아이콘이 사라지는 버그를 수정하였습니다
**타입**
**작업 사항**
- 프로필 컴포넌트 렌더링 시점에도 유저 데이터 가져올 수 있도록 effect 의존성 배열 빈 배열 추가
> fix: 마이페이지 이외 페이지에서 로그인시 프로필 아이콘 사라지는 버그 수정

- src/app/(home)/favorite-meetings/components/CardList/CardList.tsx
- src/app/(home)/favorite-meetings/layout.tsx
**개요**
- 찜한 모임 데이터 없을 때 UI 를 처리했습니다
**타입**
**작업 사항**
- 찜한 모임 데이터 없을 때 UI 를 추가하였습니다
> fix: 찜한 모임 데이터 없을 때 UI 처리

- src/components/GNB/ProfileTooltip.tsx
**개요**
- 간단한 PR 요약 내용
프로필사진 없을경우 헤더에 프로필이 안 보이는 현상 해결
**타입**
**작업 사항**
프로필 사진 없을 경우 헤더에 프로필 툴팁이 보이지 않음
프로필 사진 없을 경우 기본 사진이 들어가도록 처리함
> fix: 프로필사진 없을경우 헤더에 프로필이 안 보이는 현상 해결

- jest.config.ts
**개요**
- 간단한 PR 요약 내용
Jest가 절대경로 인식하도록 함
**타입**
- [V] ⚙️config: npm 모듈 설치 , 설정 파일 추가, 라이브러리 추가 등
**작업 사항**
Jest가 절대경로 인식하도록 함
> config: Jest가 절대경로 인식하도록 함

- src/app/(home)/all-reviews/ReviewsPage.tsx
- src/app/(home)/all-reviews/page.tsx
- src/context/FilterContent.tsx
- src/hooks/query/useFetchReviewData.tsx
- src/service/reviewService.ts
- src/types/reviewType.ts
**개요**
모든 리뷰 페이지에서 리뷰 초기 데이터를 SSR로 가져오는 작업을 완료했습니다.
**타입**
**작업 사항**
- 기존 코드에서 prefetchInfiniteQuery로 초기 데이터를 prefetch -> queryKey값이 모든 리뷰의 react-query queryKey값과 일치 하지 않아 동작하지 않았음 -> queryKey값을 일치 시키는 코드 추가
- queryKey값을 일치 시키기 위해 sortBy를 받아야하는데, page마다 sortBy가 달라 sortBy를 받는 props 추가
- reviewQueryType 오류부 수정
- 스크린샷
>  refactor: 모든 리뷰 리뷰 초기 데이터 SSR (218번 이슈 새로운 브랜치에서 배포 테스트)

- src/components/ProgressBar/ProgressBar.tsx
**개요**
- Progressbar 컴포넌트가 표시하고자 하는 비율을 제대로 반영하지 못하는 버그를 수정하였습니다
**타입**
**작업 사항**
- 애니메이션이 없을 때 프로그레스바에 `width` 속성을 `px` 단위가 아니라 `%` 로 변경
- 전
- 후
> fix: 모든 리뷰 페이지 인원 비율 progressbar 진행도에 반영 안되는 현상 수정

- next.config.ts
- src/api/detail-meeting/cancelGroup.ts
- src/api/detail-meeting/getDetailMeetingDate.ts
- src/api/detail-meeting/joinGroup.ts
- src/api/detail-meeting/participantsGroup.ts
- src/api/getUserData.ts
- src/api/meeting/createMeeting.ts
- src/api/meeting/getMeetingAttendee.ts
- src/api/meeting/getMeetingDate.ts
- src/api/userAuth.ts
- src/api/users.ts
- src/constants/index.ts
- src/service/reviewService.ts
**개요**
env 수정 및 일괄 적용
**타입**
**작업 사항**
빌드  시, next build 에러가 있어 env를 수정하고, 일괄 변경 했습니다.
> fix: env 수정

- .github/workflows/main.yml
**개요**
workflow main.yml 파일에 .env 파일 생성 단계를 추가하였습니다.
**타입**
> fix: workflow yml 수정

- src/components/InputSection/InputWindow.tsx
**개요**
- 간단한 PR 요약 내용
style: input 창 스타일 변경
**타입**
- [V ] 🎨style: 코드 스타일 및 포맷 / CSS 등 사용자 UI 디자인 변경 (제품 코드 수정 발생, 코드 형식, 정렬 등의 변경)
**작업 사항**
input 보더를 rounded로 변경함
> style: input 창 스타일 변경

- src/app/(home)/all-reviews/_components/ReviewCardList.tsx
**개요**
모든 리뷰 카드 리스트 관련 코드를 수정하였습니다! (로딩상태 추가, 초기 데이터 limit 값 수정)
**타입**
**작업 사항**
- 리뷰 카드리스트의 로딩 상태를 추가했습니다
- 리뷰 카드에서 중복 되었던 키 값을 제거 했습니다
> fix: 모든 리뷰 카드 리스트 관련 코드 수정(로딩상태 추가, limit 값 수정)

- src/components/Filtering/FIlterListCustom.tsx
- src/components/PageNav/PageNavbarCustom.tsx
- src/hooks/customs/useFilters.tsx
- src/types/filterType.ts
**개요**
필터링 Context API -> Custom hook으로 변경을 위한 코드를 추가했습니다.
커스텀 훅 변경에 맞게 Filtering List와 PageNav 코드 리팩토링 버전을 FilterListCustom, PageNavbarCustom 이라는 이름으로 추가했습니다. 
❗다른 페이지에서 필터링 변경 시 FilterListCustom, PageNavbarCustom 컴포넌트를 사용해주시고
적용이 끝나면 추후에 일괄적으로 이전 필터링 관련 코드 삭제하겠습니다!
**타입**
**작업 사항**
- 필터링 관련 타입 지정
- custom hook 추가
- custom hook에 맞게 FilterList, PageNavbar 코드 리팩토링
> feat: 필터링 커스텀 훅, 타입 추가

- src/api/getUserData.ts
- src/components/Login/Login.tsx
- src/hooks/customs/useAuth.tsx
- src/store/useAuthStore.tsx
- src/types/userType.ts
**개요**
- 간단한 PR 요약 내용
refactor: user 전역상태변수에 setState 추가 및 활용
**타입**
- [ V ] ♻️refactor: 코드 리팩토링
**작업 사항**
user 전역상태변수에 setState를 추가하여, 객체로 값을 간단하게 바꿀 수 있도록 함
> refactor: user 전역상태변수에 setState 추가 및 활용

- src/components/Modal/ErrorModalContent.tsx
- src/hooks/customs/useErrorHandler.tsx
- src/lib/ReactQueryProvider.tsx
**개요**
- 리뷰 생성 후 발생하는 에러를 공통으로 처리할 수 있도록 mutationCache를 적용하였습니다
**타입**
**작업 사항**
- 에러 발생 시 출력되는 모달 wrapper 함수 `useErrorHandler` 추가
- 에러 모달 조합 컴포넌트로 구성하여 한 곳에 모을 수 있도록 작업
> reafactor: 리뷰 작성 관련 에러 공통화

- src/api/getUserData.ts
- src/api/meeting/myMeeting.ts
- src/api/userAuth.ts
- src/api/users.ts
- src/app/(auth)/api/route.ts
- src/app/(home)/mypage/components/CardList/CardList.tsx
- src/app/(home)/mypage/components/CardList/Services/myMeetingService.ts
- src/app/(home)/mypage/createdMeetings/page.tsx
- src/app/(home)/mypage/meetings/page.tsx
- src/app/(home)/mypage/page.tsx
- src/app/(home)/mypage/reviews/page.tsx
- src/app/(home)/mypage/reviews/writable/page.tsx
- src/app/(home)/mypage/reviews/written/components/CardList.tsx
- src/app/(home)/mypage/reviews/written/page.tsx
- src/middleware.ts
- src/types/reviewType.ts
**개요**
- 마이페이지를 SSR 하도록 변경하였습니다
**타입**
**작업 사항**
> refactor: 마이페이지 SSR 전환

- src/app/(home)/mypage/components/CardList/CardList.tsx
- src/app/(home)/mypage/components/CardList/Services/myMeetingService.ts
- src/app/(home)/mypage/components/ReviewForm/ReviewForm.tsx
- src/app/(home)/mypage/reviews/written/components/CardList.tsx
- src/hooks/customs/useCreateReview.tsx
- src/hooks/customs/useMyMeetings.tsx
- src/hooks/mutation/useReviewMutation.tsx
**개요**
- [BR7-379], [1차 QA] 관련) 리뷰 작성 시 새로고침 안 되는 현상을 react query mutation을 적용하여 수정하였습니다
**타입**
**작업 사항**
- create review 에 mutate 적용
- review 작성 요청 성공 시 관련 쿼리 key (`joined`, `review`) invalidQuery
- 관련 JIRA https://woo2zzas.atlassian.net/browse/BR7-379
> [BR7-379] fix: mutation 적용하여 리뷰 작성 후 새로고침 안 되는 버그 수정

- src/app/(home)/mypage/components/CardList/CardList.tsx
**개요**
- `useMyMeetings()` hook 에서 받아오던 모임 `참여 취소` 함수 `onCancelClick` 을 컴포넌트에서 처리하도록 분리하고, 재사용성이 없는 custom hook을 제거하였습니다
**타입**
**작업 사항**
- 컴포넌트에서 함수를 호출하도록 변경 -> `handleClickCancel` 추가
> refactor: 예약 취소 기능 custom hook에서 분리하고 컴포넌트로 종속

- src/app/(home)/all-reviews/page.tsx
**개요**
prefetch 시 누락된 타입때문에 모든 리뷰에 워케이션, 달램핏이 모두 포함되는 오류를 고쳤습니다
**타입**
> fix: 초기데이터 필터 타입 누락 수정

- src/app/(home)/favorite-meetings/components/CardList.tsx
- src/app/(home)/favorite-meetings/components/PageContent.tsx
- src/app/(home)/favorite-meetings/layout.tsx
- src/app/(home)/favorite-meetings/page.tsx
- src/hooks/customs/useFavoriteMeetings.tsx
**개요**
- #245 `useFilters` 변경 사항을 반영하여 관련 코드를 수정하였습니다
**타입**
**작업 사항**
- `FilterProvider` 컴포넌트 제거
- `PageNav` 와 `CardList`를 묶는 `PageContent` 컴포넌트 추가
- `useFilters` hook 사용으로 변경 -> `initialType` 매개변수로 전달
> refactor: use filter custom hook 변경 반영

- src/app/(home)/all-reviews/ReviewsPage.tsx
- src/app/(home)/all-reviews/_components/ReviewCardList.tsx
- src/app/(home)/all-reviews/_components/ReviewSummary.tsx
- src/app/(home)/all-reviews/page.tsx
- src/hooks/query/useFetchReviewData.tsx
- src/hooks/query/useFetchReviewsScore.tsx
**개요**
필터링이 custom hook로 변경되면서, 모든 리뷰 페이지를 필터링 상태관리 custom hook에 맞게 코드를 변경하였습니다!
**타입**
**작업 사항**
- 필터링 방식 변경으로 props가 필요한 컴포넌트에 props를 넣어줬습니다.
- api도 마찬가지로 호출하는 컴포넌트에서 filter 값을 props로 전달받아 query key에 넣어줬습니다.
> refactor: 모든 리뷰 페이지 필터링 방식 변경에 따른 코드 변경

- src/components/Login/Login.tsx
**개요**
- 간단한 PR 요약 내용
fix: 로그인시 프로필 이미지 불러오지 않는 오류 해결
**타입**
**작업 사항**
로그인 시 상태변수에 이미지 설정이 빠져있었습니다. 추가하여 fix했습니다
> fix: 로그인시 프로필 이미지 불러오지 않는 오류 해결

- src/api/meeting/getMeetingDate.ts
- src/app/(home)/MainPage.tsx
- src/app/(home)/all-reviews/ReviewsPage.tsx
- src/app/(home)/page.tsx
- src/components/MainCard/CardListInfinite.tsx
- src/hooks/query/useHomeMeetingCardList.ts
**개요**
- filter 방식 수정
**타입**
**작업 사항**
> fix: filter 방식 수정

- .gitignore
- next-pwa.d.ts
- next.config.ts
- package-lock.json
- package.json
- public/manifest.json
- src/app/layout.tsx
**개요**
- PWA 적용
- PWA 빌드로 생성된, 파일들 gitignore에 추가
- 아직 이미지, 배경, 이름설정은 하지않은 상태
**타입**
**작업 사항**
- PWA 적용
- PWA 빌드로 생성된, 파일들 gitignore에 추가
- 아직 이미지, 배경, 이름설정은 하지않은 상태
> feat: PWA 적용

- src/api/userAuth.ts
- src/app/(auth)/api/route.ts
- src/hooks/customs/useAuth.tsx
**개요**
- 존재하지 않는 이메일을 입력하는 등의 로그인 실패 시 에러 메시지가 출력 안되는 현상을 수정하였습니다
**타입**
**작업 사항**
- 기존 `signUser` 함수를 route handler가 간섭하지 않도록 변경
- 로그아웃 시 쿠키 삭제하는 route handler 추가 -> logoutUser 함수 async 함수로 변경
> fix: 로그인 실패 시 에러 메시지 출력 안 되는 버그 수정

- src/app/(home)/meeting/_components/footer.tsx
- src/hooks/query/useParticipantsData.ts
**개요**
디테일페이지 참가여부 react-query로 데이터 패칭
**타입**
**작업 사항**
디테일페이지 참가여부 react-query로 데이터 패칭
> feat: paricipants-reactquery

- src/app/(home)/meeting/[id]/DetailClient.tsx
- src/app/(home)/meeting/[id]/ReviewClient.tsx
- src/app/(home)/meeting/_components/MeetingCard.tsx
- src/types/meetingDetail.ts
**개요**
- 기획에 맞춰 디테일페이지 수정
- 디테일 박스에 type대신 name으로 출력
- 리뷰에 이미지 제거
- 리뷰 타입 type대신 name으로 변경
**타입**
**작업 사항**
- 기획에 맞춰 디테일페이지 수정
- 디테일 박스에 type대신 name으로 출력
- 리뷰에 이미지 제거
- 리뷰 타입 type대신 name으로 변경
> fix: 기획에 맞춰 디테일페이지 수정

- src/components/Button/LikeButton.tsx
**개요**
찜하기 버튼 클릭 시 디테일 페이지로 가는 오류를 수정하였습니다.
**타입**
**작업 사항**
- 찜하기 버튼에 이벤트가 상위 엘리먼트에 전달되지 않게 막아 주는 stopPropagation과 preventDefault 코드를 추가하였습니다.
**스크린샷**
> fix: 찜하기 버튼 클릭 시 디테일 페이지로 이동 오류 코드 수정

- next.config.ts
- package-lock.json
- package.json
**개요**
feat: 번들 확인 라이브러리 설치
**타입**
**작업 사항**
feat: 번들 확인 라이브러리 설치
> feat: 번들 확인 라이브러리 설치

- src/components/Filtering/__tests__/FilterDropdown.test.tsx
- src/components/Filtering/__tests__/FilterListCustom.test.tsx
**개요**
FilterList 관련 테스트 코드를 작성하였습니다.
**타입**
**작업 사항**
- FilterDropdown.test.ts
- 기본 props로 정상적으로 렌더링되는지 테스트
- isOpen이 true일 때 드롭다운 메뉴가 표시되는지 테스트
- 버튼 클릭 시 onToggle이 호출되는지 테스트
- 외부 클릭 시 드롭다운이 닫히는지 테스트
<정렬 관련>
- sort일 때 정렬 아이콘이 렌더링되는지 테스트
<날짜 관련>
- 캘린더 컴포넌트가 렌더링되는지 테스트
---
- FilterListCustom.test.ts
- 기본 props로 정상적으로 렌더링되는지 테스트
- 비활성화된 필터는 렌더링되지 않는지 테스트
<지역 관련>
- 지역 선택 시 handleFilter가 올바르게 호출되는지 테스트
<날짜 관련>
- 날짜 필터가 활성화되어 있을 때 캘린더가 렌더링되는지 테스트
- 날짜가 선택되었을 때 선택된 날짜가 표시되는지 테스트
- 날짜 필터 초기화 시 "날짜 전체"가 표시되는지 테스트
<정렬 관련>
- 모임 정렬 필터 변경 시 handleFilter가 올바르게 호출되는지 테스트
- 모집 마감순 선택 시 자동으로 오름차순으로 변경되는지 테스트
> test: filterList 관련 테스트 코드 작성

- src/components/PageNav/__tests__/PageNavbarCustom.test.tsx
**개요**
paegNavbar 테스트 코드를 작성하였습니다.
**타입**
**작업 사항**
- 메인 네비게이션 버튼이 올바르게 렌더링되는지 테스트
- 메인 버튼 클릭 시 onMainClick이 호출되고 상태가 변경되는지 테스트
- 서브 버튼 클릭 시 onSubClick이 호출되고 상태가 변경되는지 테스트
- 필터 prop이 전달되었을 때 올바르게 초기 상태가 설정되는지 테스트
- 초기 렌더링 시 올바른 버튼이 선택되는지 테스트
- 마이페이지 경로에서 올바르게 동작하는지 테스트
> test: pageNavbar 테스트 코드

- src/app/(home)/_components/CreateMeetingForm.test.tsx
**개요**
- 간단한 PR 요약 내용
**타입**
**작업 사항**
> test: 모임 만들기 테스트코드

- src/app/(home)/mypage/components/ProfileForm/FormControl.tsx
- src/app/(home)/mypage/components/ProfileForm/ProfileForm.test.tsx
- src/app/(home)/mypage/components/ProfileForm/ProfileForm.tsx
- src/app/(home)/mypage/components/ProfileIcon/ProfileIcon.test.tsx
- src/app/(home)/mypage/components/ProfileIcon/ProfileIcon.tsx
**개요**
- 프로필 수정 테스트 코드를 작성하였습니다
**타입**
**작업 사항**
- 기본 test 코드 작성 
-  초기 렌더링 테스트
- 입력값 변경됐을 때 수정하기 버튼 상태 잘 처리하는지 확인
- 이메일 필드 readonly 처리됐는지 확인
- 폼 제출 했을 때 api 호출하는지 확인 ----> &lt;form&gt;에 `role='form'` 속성 추가
- 취소 버튼 클릭했을 때 함수 실행되는지 확인
- `ProfileIcon.tsx` 컴포넌트의 조합 컴포넌트 패턴이 제대로 동작하는지 확인 ---- > &lt;svg&gt;에 `role='img'` 속성 추가
> test: 프로필 폼 테스트 코드 작성

- src/hooks/customs/__tests__/useFilters.test.ts
**개요**
필터링 커스텀 훅인 useFilters 테스트 코드를 작성하였습니다.
**타입**
**작업 사항**
- 초기 필터 값이 올바르게 설정되는지 확인
- handleChangeFilter가 각 필터를 변경하는지 확인
- onFilter가 호출되는지 확인
> test: useFilters 테스트 코드 작성

- src/app/(home)/meeting/_components/footer.test.tsx
**개요**
- footer mock을 이용하여 test코드 작성
**타입**
**작업 사항**
- footer mock을 이용하여 test코드 작성
> test: footer component test code
