src/app/(home)/mypage/page.tsx, src/components/Members/Members.tsx
**개요**
- 정원 마감시 텍스트 색상이 변경되는 기본 옵션을 선택으로 변경하였습니다.
**타입**
**작업 사항**
- 텍스트 색상을 변경할지 말지 여부를 선택하는 `highLight` prop 을 추가하였습니다.
- 기본값은 'on' 이며, 선택 props 이기 때문에 색상 변경을 원하지 않을 경우 `highLight` 을 'off'로 전달할 수 있습니다
=> feat: Members 공통 컴포넌트 정원 마감 시 하이라이팅 기능 여부 선택 옵션으로 변경

src/app/(home)/_components/HomeFilter.tsx, src/app/(home)/page.tsx, src/components/MainCard/CardList.tsx, src/store/useInputSelectFilterStore.tsx
**개요**
- 채은님이 만든 필터링 컴포넌트 적용 후 필터링 기능 구현
**타입**
**작업 사항**
1. 채은님이 만든 필터링 컴포넌트는 useState를 사용하는 컴포넌트라 csr 컴포넌트로 동작
2. main page에서 채은님이 만든 컴포넌트를 import후 사용하려면 use client를 선언해야 하는 상황이 발생
※ main page에서는 ssr 방식을 유지하는게 좋다. 
1. 초기 데이터 로딩속도가 빨라 유저가 브라우저에 접속해 보여지는 Time to First Meaningful Paint (TTFMP)가 짧아 UX가 증가한다.
2. ssr 방식으로 데이터를 불러오면 html 파일에 데이터가 들어있어 seo 검색엔진 점수가 높게 나오기 유리한 상황이 된다.
3. 이러한 상황에서 main page에서 바로 csr 컴포넌트를 적용하는 방법이 아닌 새로운 컴포넌트를 만들어 그 안에 적용
```js
src -> app -> (home) -> _components -> HomeFilter.tsx
'use client';
import FilterList from '@/components/Filtering/FIlterList';
import { useFilterStore } from '@/store/useInputSelectFilterStore';
import React, { useEffect } from 'react';
export default function HomeFilter() {
const { selectedFilters, setSelectedFilters } = …
```
=> 채은님이 만든 필터링 컴포넌트 적용 후 필터링 기능 구현

src/app/(home)/_components/HomeFilter.tsx, src/app/(home)/all-reviews/page.tsx, src/components/Filtering/FIlterList.tsx, src/components/Filtering/Filter.tsx, src/components/PageNav/PageNavbar.tsx, src/constants/index.ts, src/store/useInputSelectFilterStore.tsx
**개요**
카드, 리뷰 api 호출 시 적용해야 할 파라미터 값을 pageNav+filtering 하나의 스토어에서 전역 상태 값으로 가져올 수 있게 되었습니다! 
**타입**
**작업 사항**
- 리뷰카드, 모임 카드의 필터링 내용을 하나의 zustand 스토어에서 관리하기 위해 useFilterStore를 만들었습니다.
- pageNav, filterList에서 useEffect을 사용해 스토어에 저장될 값들을 실시간으로 저장합니다.
- 스크린샷
=> feat: pageNav, filtering에서 전역 상태 하나의 store로 관리 구현

src/api/users.ts, src/app/(home)/mypage/components/ProfileForm/Input.tsx, src/app/(home)/mypage/components/ProfileForm/ProfileForm.tsx, src/app/(home)/mypage/components/ProfileInput/ProfileInput.tsx
**개요**
- 프로필에서 회사명을 수정 기능을 추가하였습니다
**타입**
**작업 사항**
- `.env` 파일의 BASE_URL 변경을 반영하여 api endpoint를 수정하였습니다
- 마이페이지의 프로필 수정 버튼을 눌러 프로필 수정 기능을 추가하였습니다
- 프로필의 회사명이 빈 값인 경우 버튼이 활성화되지 않도록 하였습니다
- 남은 할 일
- 프로필 수정 후 새로고침 되지 않는 현상 --> react query useMutation 적용하여 쿼리 key refetch 요청으로 변경 예정
-
=> feat: 마이페이지 - 프로필 회사명 수정 기능 추가

src/app/(home)/_components/HomeFilter.tsx, src/app/(home)/all-reviews/page.tsx, src/app/(home)/page.tsx, src/components/Filtering/FIlterList.tsx, src/components/PageNav/PageNavbar.tsx, src/context/FilterContent.tsx, src/hooks/customs/useFetchReviews.tsx, src/hooks/customs/useFilter.tsx, src/hooks/query/useFetchReviewsScore.tsx, src/types/filterType.ts, src/types/reviewType.ts
**개요**
필터링 상태를 전역으로 관리하던 zustand를 쓰지않고, context API를 추가했습니다.
**타입**
**작업 사항**
- 페이지 별 전역 상태가 관리 가능한 Context API를 추가했습니다. (추후 zustand 관련 코드를 삭제할 예정입니다.)
- 기존 코드에서 Zustand 스토어에서 가져온 값들을  Context API을 이용한 custom Hook(useFilter)로 가져오는 것으로 변경했습니다.
-  Context API 관련 타입 파일(FilterContextType )을 추가했습니다.
- GetReviewsParams과  ReviewQueryType의 타입을 
type?: '' | 'DALLAEMFIT' | 'OFFICE_STRETCHING' | 'MINDFULNESS' | 'WORKATION'; 애서 확장성을 위해  string으로 변경하였습니다.
- 스크린샷
=> feat: filtering state 관련 Context API 추가 및 기존 코드 Context API에 맞게 변경

src/app/(home)/favorite-meetings/components/CardList/CardList.tsx, src/app/(home)/favorite-meetings/page.tsx, src/hooks/customs/useFavoriteMeetings.tsx
**개요**
- 모임 찾기의 카드리스트와 공통화하여 사용하던 custom hook을 분리하였습니다
**타입**
**작업 사항**
- `useFavoriteMettings` custom hook을 추가하였습니다
- `useFavoriteMettings` hook 은
1. 로컬 스토리지의 찜한 모임 id 를 기반으로 모임 정보를 fetch합니다
2. 찜하기를 취소하면 클라이언트에서 필터링하여 해당 모임 정보를 삭제합니다
- 남은 할 일
- 로컬 스토리지에서 찜한 id 가져오는 로직 공통화하기
- 찜 버튼 클릭/해제 시 핸들러 적용
=> feat: 찜한 모임 카드리스트 hook 분리

src/hooks/customs/useLikeNotify.tsx, src/store/useNotificationStore.tsx
**개요**
- 찜한 모임 알림 뱃지 전역 상태 관리를 추가하였습니다
**타입**
**작업 사항**
- 알림 뱃지를 전역으로 관리할 수 있게 `useNotificationStore` 전역 상태 변수를 추가하였습니다
- 찜하기와 관련된 알림 상태를 관리할 수 있도록 `useLikeNotify` 커스텀 hook 을 추가하였습니다
- 남은 할 일
- 찜하기 버튼 컴포넌트와 동기화하기
- GNB 컴포넌트에서 찜하기 알림 상태 표시하기
=> feat: 찜한 모임 알림 뱃지 상태 관리 useNotificationStore 추가

src/app/(home)/mypage/components/CardList/CardBase.tsx, src/app/(home)/mypage/components/CardList/CardInfo.tsx, src/app/(home)/mypage/components/CardList/CardList.tsx, src/app/(home)/mypage/components/CardList/CreateReviewButton.tsx, src/app/(home)/mypage/createdMeetings/page.tsx, src/app/(home)/mypage/page.tsx, src/hooks/customs/useMyMeetings.tsx
**개요**
- 마이페이지 모임 참여 취소 기능을 추가하였습니다
**타입**
**작업 사항**
- `onCancelClick` 을 prop으로 전달하여 모임 참여 취소 api 호출을 하였습니다
- 임시로 prop으로 전달하고 있어서 향후 `useMutation` 과 custom hook 안에서 관리할 수 있도록 로직 분리 예정입니다
- 내가 참여한 모임 페이지에서 custom hook 호출 시 타입 오류를 `nullish` 병합 연산자로 수정하였습니다
- 남은 할 일
- dialog 버튼 색 차이 없는 UI 수정  
=> feat: 마이페이지 모임 참여 취소 기능 추가

src/hooks/customs/useLikeNotify.tsx
**개요**
- `useLikeNotify` hook 에서 찜한 상태 전역 변수를 반환하도록 추가하였습니다
**타입**
**작업 사항**
-  `useLikeNotify` hook 에서 찜한 상태 전역 변수를 반환하도록 추가하였습니다
- 남은 작업
- 현재 `useNotificationStore` 에서 관리하고있는 찜한 페이지 찜 개수의 초기 상태 값이 `count` 가 0으로 고정되어 있어 로컬 스토리지에서 초기 값을 가져오는 `persist`의 적용이 필요합니다 
=> feat: useLikeNotify hook 에서 찜한 개수 바로 불러올 수 있도록 상태 추가

src/app/(home)/favorite-meetings/components/CardList/CardList.tsx, src/hooks/customs/useFavoriteMeetings.tsx
**개요**
- 찜한 모임 페이지에서 사용자가 찜하기를 취소했을 때 해당 아이템이 보이지 않도록 처리하였습니다
**타입**
**작업 사항**
- 찜한 모임 페이지에서 찜하기를 취소하면 서버에 추가 모임 정보를 요청하지 않고 클라이언트에서 필터링할 수 있도록 구현하였습니다
- 리액트 쿼리 키 동적 생성을 위해 로컬 스토리지에 저장된 찜한 모임 id를 문자열로 생성하여 상태 변수로 관리하였습니다
- 현재는 다른 브랜치에서 아직 안 합쳐와서 주석 처리되어 있는 상태입니다 
- 다음에 해야 할 일
- stale 타임 지정, inactivateQuery 지점 정하기
- 쿼리 key 를 동적으로 생성할 때 해시값 비교 여부 판단
=> feat: 찜한 모임에서 찜하기 취소 시 아이템 삭제 기능 추가(+ 모임 제목 출력)

src/app/(home)/favorite-meetings/layout.tsx, src/hooks/customs/useFavoriteMeetings.tsx
**개요**
- 찜한 모임 페이지의 모임 종류별 필터링 기능을 연결하였습니다
**타입**
**작업 사항**
- `useFilter` hook 이 반환하는 필터 속성들로 api 요청을 할 수 있도록 하였습니다
- `FilterProvider` contextAPI를 찜한 모임 페이지 `layout.tsx`에 적용하였습니다
-
=> feat: 찜한 모임 페이지 모임 종류 필터링 추가

src/app/(home)/mypage/components/ProfileForm/ProfileForm.tsx
**개요**
- 프로필 사진이 없을 때 프로필 유효성 검사 value 값 검사 시 null 값을 처리하지 못한 오류를 수정하였습니다
**타입**
**작업 사항**
- 유효성 검사 변경 : 이미지 없고, 회사명 빈 값일 경우 -> 회사명만 빈 값일 경우로 false 처리
- 프로필 사진이 없는 유저의 정보를 받아올 경우 `image: null` 을 빈 문자열로 처리
=> fix: 프로필 사진 없을 시 프로필 폼 진입 오류 수정

src/hooks/customs/useAuth.tsx, src/store/useNotificationStore.tsx
**개요**
- 로그아웃시 사용자의 알림을 초기화하는 기능을 추가하였습니다
**타입**
**작업 사항**
- `useNotificationStore` 전역 상태 변수에 `resetNotifications` 상태 set 함수 추가
- 로그아웃 시 실행되도록 `useAuth` custom hook `logoutUser` 에서 호출
-
=> feat: 로그아웃 시 알림 뱃지 초기화 기능 추가

src/app/(home)/mypage/components/ProfileForm/ProfileForm.tsx, src/app/(home)/mypage/components/ProfileHeader/ProfileHeader.tsx, src/components/GNB/ProfileTooltip.tsx
**개요**
- 프로필 수정시 헤더에는 적용되지 않는 버그를 헤더에도 적용되게 임시 수정하였습니다
**타입**
**작업 사항**
- profile 이미지 수정 후 modal 닫았을 때 실행되는 `router.back()` 호출 후 1초 뒤 해당 페이지를 refresh 하도록 추가(진짜 임시)
- `router.back()` 으로 변경된 `pathname` 을 감지하여 프로필 수정 이후 다시 설정하도록 변경(전역 상태를 호출하도록 변경 예정, 진짜 임시)
- 이후 추가하겠습니다
=> fix: 프로필 수정시 헤더에도 적용되게 임시 적용

src/hooks/customs/useFavoriteMeetings.tsx
**개요**
- 찜한 모임 가져오는 query 에 enabled 속성을 추가하여 좋아요한 사람을 가져올 수 없을 때에는 실행되지 않도록 수정하였습니다
**타입**
**작업 사항**
- enabled 속성 추가로 불필요한 캐싱 최소화
=> fix: 찜한 모임 가져오는 쿼리에 enabled 속성 추가

src/app/(home)/mypage/components/ProfileForm/ProfileForm.tsx, src/app/(home)/mypage/components/ProfileHeader/ProfileHeader.tsx, src/app/(home)/mypage/components/ProfileInput/ProfileInput.tsx, src/components/GNB/ProfileTooltip.tsx, src/store/useAuthStore.tsx
**개요**
- 프로필 수정 시 바로 헤더에 적용되도록 전역 변수를 사용하도록 변경하였습니다
**타입**
**작업 사항**
- 유저 전역 변수에 프로필 관련 custom hook 추가
- 💁‍♀️따로 분리한 이유? -> 필요한 상태 관리 로직을 customhook 으로 반환하려는 의도  
[참고]https://hyunjinee.notion.site/Working-with-Zustand-73c2d6bbb53d4c6e9944ddc5e23706a1#2cb39464db75424fbe00cdd2a42e14ec
- 일부 컴포넌트 개별 사용자 정보 api 호출하는 useEffect 제거 및 전역 변수 사용하도록 변경
- `ProfileForm.tsx`
- `ProfileHeader.tsx`
- `ProfileTooltip.tsx`
-
=> refator: 프로필 수정 시 바로 헤더에 적용되도록 전역 변수 사용

src/api/getReveiwScore.ts, src/app/(home)/all-reviews/_components/ReviewSummary.tsx, src/hooks/query/useFetchReviewsScore.tsx
**개요**
리뷰 평점을 타입 + 다른 필터링이 걸려도 리뷰 평점이 바뀌는 방식 -> 타입이 바뀔 때만 리뷰 평점이 바뀌는 방식
변경이유: 장소, 날짜까지 필터링된 평점 평균을 보여줄 필요는 없을 것 같다고 판단
**타입**
**작업 사항**
- 필터링된 리뷰들의 gahteringId를 받아 리뷰 평점을 바꾸는 방식 -> gatheringId를 받지 않는 방식으로 변경
- 스크린샷
https://github.com/user-attachments/assets/bb4f718f-e67b-42ac-92d3-7ca1ee9757bb
=> refactor: 리뷰 평점 리팩토링 (기획상의 변경)

src/app/(home)/mypage/components/ProfileHeader/ProfileHeader.tsx, src/app/(home)/mypage/components/ProfileInput/ProfileInput.tsx
**개요**
- 1차 QA - `백그라운드 예시` 관련 마이페이지의 프로필 수정 폼과 프로필 헤더에서 기본 배경색 처리하였습니다
**타입**
**작업 사항**
- `/icons/profileDefault.svg` 적용
- 전
- 후
=> [1차 QA 반영] style: 마이페이지에서 프로필 사진 기본 배경색 처리

src/components/ReviewCard/ReviewCard.tsx
**개요**
모든 리뷰 페이지 css 변경 및 리뷰 더보기 기능 추가
**타입**
**작업 사항**
- 리뷰 조회 시 글자를 300자로 제한하여 더보기 기능을 추가하였습니다.
- 리뷰 카드 이미지 섹션에서 적용되지 않는 코드를 삭제하고, 이미지 크기를 변경하였습니다.
- 구분선 스타일을 변경하였습니다. 
테스트 해둔 리뷰의 길이가 길어짐에 따라 피그마대로 구분선을 적용하는 것보다, 리뷰 조회 시 최대한 리뷰 내용을 확인하면 좋겠다는 생각이 들었습니다. 현재 피그마와 다르게 sm~md사이의 배치를 다르게 가져갔고,  구분선 스타일을 디테일과 모든 리뷰에서 동일하게 설정하였습니다. 아래 스크린샷을 참고하시고 어색한 부분이 있으면 말씀해주세요🤗
- 동영상 (모든리뷰)
https://github.com/user-attachments/assets/907115f5-f59b-4ff1-be19-d2e3c9ac1633
- 스크린샷 (디테일) : 리뷰에서 이미지를 제거하면 적용되는 모습
=> style: 모든 리뷰 페이지 style 변경 및 더보기 추가

src/components/GNB/ProfileTooltip.tsx
**개요**
- 간단한 PR 요약 내용
fix: 프로필 툴팁 외부 클릭시 사라지도록 함
**타입**
- [V ] ✨feat: 기능 추가, 수정, 삭제
**작업 사항**
기존: 프로필 이미지를 클릭해야만 툴팁이 닫힘
현재: 툴팁 외부를 클릭해도 툴팁이 닫힘
=> feat: 프로필 툴팁 외부 클릭시 사라지도록 함

src/app/(home)/all-reviews/_components/ReviewCardList.tsx, src/components/ReviewCard/ReviewCard.tsx
**개요**
모든 리뷰에서 날짜를 필터링이 안되는 부분이 있어 로직을 추가하였습니다.
-> 백엔드 api 오류 수정으로 인해 코드 추가 로직 부분을 삭제하였습니다.
**타입**
**작업 사항**
모임 날짜와 필터링의 날짜를 비교하는 로직을 추가해, 일치하는 리뷰 데이터만 나오게 구현하였습니다. (삭제한 로직)
리뷰 카드에 모임 날짜도 추가하였습니다.
모든 리뷰에서는 api 파라미터로 모임날짜, 모임 모집 마감 날짜를 받는데 파라미터를 활용하기 위해 날짜 필터링을 모임날짜로 설정하였습니다. 리뷰에서는 리뷰 날짜로 필터링 하지 않는 동작이 어색할 수도 있을 것 같아 모임 날짜를 카드에 추가하였습니다!
- 스크린샷
=> fix: 리뷰 날짜 필터링 코드 수정 (재수정)
